# Mengimport Library

In [1]:
import tensorflow as tf

In [6]:
const_a = tf.constant([1,2,3,4],shape=(2,2),dtype=tf.float32)
const_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [11]:
zeros_a = tf.zeros(shape=(2,2))
zeros_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>

In [15]:
fill_a = tf.fill([2,3],8.3)
fill_a

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[8.3, 8.3, 8.3],
       [8.3, 8.3, 8.3]], dtype=float32)>

In [19]:
random_a = tf.random.normal([2,2], mean=99)
random_a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[98.57104 , 98.61683 ],
       [97.200745, 98.93262 ]], dtype=float32)>

In [21]:
list_a = [1,2,3,4,5,6]

convert_a = tf.convert_to_tensor(list_a, dtype=tf.float32)

convert_a

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

## tensorflow variabel

In [22]:
var_t = tf.Variable(tf.ones([2,3]))
var_t

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [23]:
var_1 = [[2,2,2],[3,3,3]]

asign = var_t.assign(var_1)

asign

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[2., 2., 2.],
       [3., 3., 3.]], dtype=float32)>

In [24]:
tensor_i = tf.random.normal([2,2,2,3])
tensor_i

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[-0.58922935, -1.015623  ,  1.2653404 ],
         [ 0.758872  ,  0.5948655 ,  1.5391155 ]],

        [[ 0.9092827 , -0.18648525,  1.0187871 ],
         [ 0.46944544, -1.072531  , -1.2689781 ]]],


       [[[ 0.7533275 , -1.17626   ,  0.9512884 ],
         [ 0.05153544, -0.9569087 ,  1.3827094 ]],

        [[-0.55270946,  1.0652399 ,  0.8575989 ],
         [-0.17136715,  1.6075445 ,  1.3356692 ]]]], dtype=float32)>

In [27]:
tensor_i[0,...]

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[-0.58922935, -1.015623  ,  1.2653404 ],
        [ 0.758872  ,  0.5948655 ,  1.5391155 ]],

       [[ 0.9092827 , -0.18648525,  1.0187871 ],
        [ 0.46944544, -1.072531  , -1.2689781 ]]], dtype=float32)>

In [33]:
tensor_i[::-1,...]

<tf.Tensor: shape=(2, 2, 2, 3), dtype=float32, numpy=
array([[[[ 0.7533275 , -1.17626   ,  0.9512884 ],
         [ 0.05153544, -0.9569087 ,  1.3827094 ]],

        [[-0.55270946,  1.0652399 ,  0.8575989 ],
         [-0.17136715,  1.6075445 ,  1.3356692 ]]],


       [[[-0.58922935, -1.015623  ,  1.2653404 ],
         [ 0.758872  ,  0.5948655 ,  1.5391155 ]],

        [[ 0.9092827 , -0.18648525,  1.0187871 ],
         [ 0.46944544, -1.072531  , -1.2689781 ]]]], dtype=float32)>

In [37]:
image_x = [0]
tf.gather(tensor_i,indices=image_x)

<tf.Tensor: shape=(1, 2, 2, 3), dtype=float32, numpy=
array([[[[-0.58922935, -1.015623  ,  1.2653404 ],
         [ 0.758872  ,  0.5948655 ,  1.5391155 ]],

        [[ 0.9092827 , -0.18648525,  1.0187871 ],
         [ 0.46944544, -1.072531  , -1.2689781 ]]]], dtype=float32)>

In [38]:
image_x = [[0,1,1,2],[1,1,1,2]]
tf.gather_nd(tensor_i, indices=image_x)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([-1.2689781,  1.3356692], dtype=float32)>

In [46]:
const_d1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
const_d1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [47]:
const_d1.shape

TensorShape([2, 3])

In [48]:
const_d1.get_shape()

TensorShape([2, 3])

In [49]:
tf.shape(const_d1)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [50]:
reshape_1 = tf.constant([[1,2,3],[4,5,6]])

print(reshape_1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [51]:
tf.reshape(reshape_1, (3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]])>

In [52]:
expand_tf = tf.random.normal([100,100,3])
expand_tf.shape

TensorShape([100, 100, 3])

In [53]:
tf.expand_dims(expand_tf, axis=0).shape

TensorShape([1, 100, 100, 3])

In [54]:
tf.expand_dims(expand_tf, axis=1).shape

TensorShape([100, 1, 100, 3])

In [55]:
tf.expand_dims(expand_tf, axis=2).shape

TensorShape([100, 100, 1, 3])

In [56]:
squeeze_sample_1 = tf.random.normal([1,100,100,3])
print("size of the original data:",squeeze_sample_1.shape)

size of the original data: (1, 100, 100, 3)


In [57]:
squeezed_sample_1 = tf.squeeze(squeeze_sample_1)
print("data size after dimension squeezing:",squeezed_sample_1.shape)

data size after dimension squeezing: (100, 100, 3)


In [60]:
trans_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
print("size of the original data:",trans_sample_1.shape)
print(trans_sample_1)

size of the original data: (2, 3)
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [62]:
transposed_sample_1 = tf.transpose(trans_sample_1)
print("size of transposed data:",transposed_sample_1.shape)
print(transposed_sample_1)

size of transposed data: (3, 2)
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)


In [64]:
broadcast_sample_1 = tf.constant([1,2,3,4,5,6])
print("original data:",broadcast_sample_1)

original data: tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [67]:
broadcasted_sample_1 = tf.broadcast_to(broadcast_sample_1,shape=[2,6])
print("broadcasted data:",broadcasted_sample_1)

broadcasted data: tf.Tensor(
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]], shape=(2, 6), dtype=int32)


In [69]:
a = tf.constant([[3, 5], [4, 8]])
b = tf.constant([[1, 6], [2, 9]])

print(tf.multiply(a, b))

tf.Tensor(
[[ 3 30]
 [ 8 72]], shape=(2, 2), dtype=int32)


In [70]:
tf.matmul(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 63],
       [20, 96]])>

In [72]:
argmax_sample_1 = tf.constant([[1,3,2],[2,5,8],[7,5,9]])
argmax_sample_1.numpy()

array([[1, 3, 2],
       [2, 5, 8],
       [7, 5, 9]])

In [76]:
max_sample_1 = tf.argmax(argmax_sample_1, axis=0)
print("locate the maximum value by column:",max_sample_1.numpy())

locate the maximum value by column: [2 1 2]


In [74]:
max_sample_2 = tf.argmax(argmax_sample_1, axis=1)
print("locate the maximum value by row:",max_sample_2.numpy())

locate the maximum value by row: [1 2 2]


In [77]:
reduce_sample_1 = tf.constant([1,2,3,4,5,6],shape=[2,3])
reduce_sample_1.numpy()


array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
tf.reduce_sum(reduce_sample_1,axis=None).numpy()


21

In [79]:
tf.reduce_sum(reduce_sample_1,axis=0).numpy()


array([5, 7, 9])

In [82]:
tf.reduce_sum(reduce_sample_1,axis=1).numpy()

array([ 6, 15])

In [83]:
concat_sample_1 = tf.random.normal([4,100,100,3])
concat_sample_2 = tf.random.normal([40,100,100,3])
print("sizes of the original data:",concat_sample_1.shape,concat_sample_2.shape)

sizes of the original data: (4, 100, 100, 3) (40, 100, 100, 3)


In [88]:
concated_sample_1 = tf.concat([concat_sample_1,concat_sample_2], axis=0)
print("size of the concatenated data:",concated_sample_1.shape)

size of the concatenated data: (44, 100, 100, 3)


In [97]:
stack_sample_1 = tf.random.normal([2,2,3])
stack_sample_2 = tf.random.normal([2,2,3])
print("sizes of the original data: ",stack_sample_1.shape, stack_sample_2.shape)


sizes of the original data:  (2, 2, 3) (2, 2, 3)


In [98]:
#Dimensions increase after the concatenation. If axis is set to 0, a dimension is added before the first dimension.
stacked_sample_1 = tf.stack([stack_sample_1, stack_sample_2],axis=0)
print("size of the concatenated data:",stacked_sample_1.shape)

size of the concatenated data: (2, 2, 2, 3)


In [99]:
tf.unstack(stacked_sample_1,axis=0)

[<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[-1.3038361 ,  1.493537  , -0.4575571 ],
         [-1.64115   ,  0.01479695, -0.69148314]],
 
        [[-0.19404233,  1.0077832 ,  1.2548472 ],
         [-0.97444975,  1.0605582 ,  0.42968935]]], dtype=float32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
 array([[[-0.5639758 ,  0.36812386, -1.5872178 ],
         [ 0.13021925, -1.0503571 , -0.78633225]],
 
        [[ 0.21349749,  0.9708791 ,  1.1109482 ],
         [-0.80331683,  1.0312077 , -1.1832316 ]]], dtype=float32)>]

In [100]:
import numpy as np
split_sample_1 = tf.random.normal([10,100,100,3])
print("size of the original data:",split_sample_1.shape)


size of the original data: (10, 100, 100, 3)


In [102]:
splited_sample_1 = tf.split(split_sample_1, num_or_size_splits=5,axis=0)
print("size of the split data when m_or_size_splits is set to 10: ",np.shape(splited_sample_1))


size of the split data when m_or_size_splits is set to 10:  (5, 2, 100, 100, 3)


In [106]:
splited_sample_2 = tf.split(split_sample_1, num_or_size_splits=[3,5,2],axis=0)
print("sizes of the split data when num_or_size_splits is set to [3,5,2]:",np.shape(splited_sample_2[0]), np.shape(splited_sample_2[1]), np.shape(splited_sample_2[2]))

sizes of the split data when num_or_size_splits is set to [3,5,2]: (3, 100, 100, 3) (5, 100, 100, 3) (2, 100, 100, 3)


In [107]:
sort_sample_1 = tf.random.shuffle(tf.range(10))
print("input tensor:",sort_sample_1.numpy())


input tensor: [8 6 0 7 4 2 1 9 5 3]


In [108]:
sorted_sample_1 = tf.sort(sort_sample_1, direction="ASCENDING")
print("tensor sorted in ascending order:",sorted_sample_1.numpy())


tensor sorted in ascending order: [0 1 2 3 4 5 6 7 8 9]


In [109]:
sorted_sample_2 = tf.argsort(sort_sample_1,direction="ASCENDING")
print("indexes of elements in ascending order:",sorted_sample_2.numpy())

indexes of elements in ascending order: [2 6 5 9 4 8 1 3 0 7]


In [110]:
values, index = tf.nn.top_k(sort_sample_1,5)
print("input tensor:",sort_sample_1.numpy())


input tensor: [8 6 0 7 4 2 1 9 5 3]


In [113]:
print("first five values in Descending order:", values.numpy())

first five values in Descending order: [9 8 7 6 5]


In [114]:
print("indexes of the first five values in Descending order:", index.numpy())

indexes of the first five values in Descending order: [7 0 3 1 8]


In [115]:
x = tf.ones((2, 2), dtype=tf.dtypes.float32)
y = tf.constant([[1, 2],[3, 4]], dtype=tf.dtypes.float32)
z = tf.matmul(x, y)
print(z)

tf.Tensor(
[[4. 6.]
 [4. 6.]], shape=(2, 2), dtype=float32)


In [117]:
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
#Create a graph and define it as a computational graph.
a = tf.ones((2, 2), dtype=tf.dtypes.float32)
b = tf.constant([[1, 2],[3, 4]], dtype=tf.dtypes.float32)
c = tf.matmul(a, b)
#Enable the drawing function, and perform the multiplication operation to obtain data.
with tf.Session() as sess:
    print(sess.run(c))

[[4. 6.]
 [4. 6.]]


In [121]:
import timeit
#Create a convolutional layer.
CNN_cell = tf.keras.layers.Conv2D(filters=100,kernel_size=2,strides=(1,1))
#Use @tf.function to convert the operation into a graph.
@tf.function
def CNN_fn(image):
    return CNN_cell(image)
image = tf.zeros([100, 200, 200, 3])
#Compare the execution time of the two modes.
CNN_cell(image)
CNN_fn(image)

<tf.Tensor 'StatefulPartitionedCall_1:0' shape=(100, 199, 199, 100) dtype=float32>

In [124]:
#Call timeit.timeit to measure the time required for executing the code 10 times.
print("Eager execution mode:", timeit.timeit(lambda: CNN_cell(image), number=10))
print("Autograph mode:", timeit.timeit(lambda: CNN_fn(image), number=10))

Eager execution mode: 0.0201985000167042
Autograph mode: 0.009555800002999604
